# 1.2.40: Cloud Build 配置 - 支持镜像层缓存加速构建
# 使用 Artifact Registry 替代已弃用的 Container Registry (gcr.io)
# 参考: https://cloud.google.com/build/docs/optimize-builds/speeding-up-builds

timeout: 1200s  # 20分钟超时

options:
  # 使用更高性能的构建机器
  machineType: 'E2_HIGHCPU_8'
  # 启用日志流
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: 拉取缓存镜像（如果存在）
  - name: 'gcr.io/cloud-builders/docker'
    id: 'pull-cache'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull ${_IMAGE}:cache || echo "No cache image found, building from scratch"

  # Step 2: 使用缓存构建新镜像
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --cache-from ${_IMAGE}:cache \
          -t ${_IMAGE}:${SHORT_SHA} \
          -t ${_IMAGE}:${_VERSION} \
          -t ${_IMAGE}:cache \
          -t ${_IMAGE}:latest \
          .
    waitFor: ['pull-cache']

  # Step 3: 并行推送所有标签
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-sha'
    args: ['push', '${_IMAGE}:${SHORT_SHA}']
    waitFor: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-version'
    args: ['push', '${_IMAGE}:${_VERSION}']
    waitFor: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-cache'
    args: ['push', '${_IMAGE}:cache']
    waitFor: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args: ['push', '${_IMAGE}:latest']
    waitFor: ['build']

# 声明构建产物
images:
  - '${_IMAGE}:${SHORT_SHA}'
  - '${_IMAGE}:${_VERSION}'
  - '${_IMAGE}:cache'
  - '${_IMAGE}:latest'

# 替换变量（由 gcloud builds submit 传入）
substitutions:
  _IMAGE: 'asia-east1-docker.pkg.dev/PROJECT_ID/yuichat/yuichat-backend'
  _VERSION: 'latest'
