# 1.3.5: Cloud Build 配置 - 使用 Kaniko 加速构建
# Kaniko 优势：
# - 更好的层缓存支持
# - 无需 Docker daemon
# - 支持 BuildKit 语法
# 参考: https://cloud.google.com/build/docs/optimize-builds/kaniko-cache

timeout: 1200s  # 20分钟超时

options:
  # 使用更高性能的构建机器
  machineType: 'E2_HIGHCPU_8'
  # 启用日志流
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1.3.5: 使用 Kaniko 构建（更好的缓存支持）
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build-and-push'
    args:
      - '--dockerfile=Dockerfile'
      - '--context=.'
      # 目标镜像（多标签）
      - '--destination=${_IMAGE}:${SHORT_SHA}'
      - '--destination=${_IMAGE}:${_VERSION}'
      - '--destination=${_IMAGE}:latest'
      # 缓存配置 - 这是加速的关键！
      - '--cache=true'
      - '--cache-ttl=168h'  # 缓存保留7天
      # 快照模式 - 更快的层检测
      - '--snapshot-mode=redo'
      # 压缩级别 - 平衡构建速度和镜像大小
      - '--compressed-caching=false'
      # 使用新的快照器（更快）
      - '--use-new-run=true'

# 替换变量（由 gcloud builds submit 传入）
substitutions:
  _IMAGE: 'asia-east1-docker.pkg.dev/PROJECT_ID/yuichat/yuichat-backend'
  _VERSION: 'latest'
